name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: npm install

      # - run: npm run compile
      # - run: npm run test
      # - run: npm run coverage
      - uses: codecov/codecov-action@v3
      # - run: pip3 install slither-analyzer && npm run slither
      # - run: npm run lint
