name: Slither

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  slither:
    name: Slither analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pip3
        run: |
          python -m pip install --upgrade pip

      - name: Install Slither
        run: |
          pip3 install slither-analyzer

      - name: Build
        run: forge build

      - name: Run Slither
        run: |
          slither --fail-high --skip-clean .
